
import React, { useState } from 'react';
import { MOCK_STUDENTS, MOCK_COURSES, MOCK_CLASSES } from '../../constants.tsx';
import { 
  ChevronLeft, 
  Calendar, 
  BookOpen, 
  Star, 
  ShieldCheck, 
  Target, 
  Clock, 
  Sparkles, 
  History, 
  CheckCircle2, 
  FileText, 
  Trophy, 
  MessageSquare, 
  ClipboardList, 
  Eye,
  MonitorPlay,
  Zap,
  TrendingUp,
  LayoutGrid,
  Download,
  Loader2
} from 'lucide-react';

interface StudentDetailViewProps {
  studentId: string;
  onClassClick: (id: string) => void;
  onBack: () => void;
  onEnterCourse: (id: string) => void;
}

export const StudentDetailView: React.FC<StudentDetailViewProps> = ({ studentId, onClassClick, onBack, onEnterCourse }) => {
  const student = MOCK_STUDENTS.find(s => s.id === studentId) || MOCK_STUDENTS[0];
  const registeredClasses = MOCK_CLASSES.filter(cls => cls.students.some(s => s.id === studentId));
  const [isExporting, setIsExporting] = useState(false);

  const mockSubmissions = [
    { type: 'quiz', title: 'Binary Logic Basics', score: '92%', date: '3 days ago', status: 'Passed', course: student.level, courseType: 'Logic' },
    { type: 'assignment', title: 'Logic Circuit Diagram', score: 'A-', date: '1 week ago', status: 'Graded', course: student.level, courseType: 'Engineering' },
  ];

  const handleExportProfile = () => {
    setIsExporting(true);
    setTimeout(() => {
      const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
      const filename = `DIR_Profile_${student.firstName}_${student.lastName}_${timestamp}.txt`;
      
      const content = `DIGITAL INFORMATION RESOURCES - LEARNER PROFILE\nName: ${student.firstName} ${student.lastName}\nID: ${student.username}\nMastery: ${student.finalGrade}%\nAttendance: ${student.attendance} Days\nStatus: ${student.status.toUpperCase()}\n---\nReport generated by LMS Engine v2.4.0`;
      
      const blob = new Blob([content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = filename;
      link.click();
      URL.revokeObjectURL(url);
      
      setIsExporting(false);
      alert('Student profile report exported successfully.');
    }, 1200);
  };

  return (
    <div className="h-full flex flex-col gap-4 overflow-hidden animate-in slide-in-from-right duration-500">
      
      {/* Dynamic Header */}
      <div className="w-full bg-[#292667] rounded-2xl p-6 text-white shadow-xl border-b-8 border-[#ec2027] flex flex-col md:flex-row items-center justify-between gap-6 flex-shrink-0 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-80 h-80 bg-white/5 rounded-full -mr-24 -mt-24 blur-3xl"></div>
        
        <div className="flex items-center gap-6 relative z-10">
           <button onClick={onBack} className="p-3 bg-white/10 rounded-xl text-white shadow-md hover:bg-[#ec2027] transition-all border border-white/10 active:scale-90">
             <ChevronLeft size={24} strokeWidth={4} />
           </button>
           <div>
             <h2 className="text-2xl font-black leading-none tracking-tight uppercase">{student.firstName} <span className="text-[#ec2027]">{student.lastName}</span></h2>
             <div className="flex items-center gap-2 mt-2">
                <span className={`px-2 py-0.5 rounded-md text-[9px] font-black uppercase text-white ${student.status === 'active' ? 'bg-[#00a651]' : 'bg-slate-500'}`}>{student.status}</span>
                <span className="text-[10px] font-black text-[#ec2027] uppercase tracking-widest opacity-60">ID: {student.username}</span>
             </div>
           </div>
        </div>

        <div className="flex items-center gap-8 px-6 md:border-l-2 border-white/10 relative z-10">
           <div className="text-center">
              <p className="text-3xl font-black text-[#ec2027] leading-none mb-1">{student.finalGrade}%</p>
              <p className="text-[9px] font-black uppercase text-white/40 tracking-widest">Mastery</p>
           </div>
           <div className="w-px h-10 bg-white/10"></div>
           <div className="text-center">
              <p className="text-3xl font-black text-[#00a651] leading-none mb-1">{student.attendance}</p>
              <p className="text-[9px] font-black uppercase text-white/40 tracking-widest">Attendance</p>
           </div>
        </div>
      </div>

      <div className="flex-1 grid grid-cols-1 lg:grid-cols-12 gap-4 overflow-hidden pb-1">
        <div className="lg:col-span-4 flex flex-col gap-4 overflow-hidden">
           <div className="bg-white rounded-3xl p-6 shadow-md border border-slate-100 text-center flex-shrink-0 relative group">
             <img src={`https://picsum.photos/seed/${student.id}/300`} className="w-32 h-32 mx-auto rounded-[2rem] border-4 border-white shadow-xl mb-4 object-cover" alt="" />
             <h3 className="text-lg font-black text-[#292667] uppercase leading-none truncate mb-1">{student.firstName} {student.lastName}</h3>
             <p className="text-[9px] font-black text-[#ec2027] uppercase tracking-widest mb-4">Verified Learner</p>
             <button 
                onClick={handleExportProfile}
                disabled={isExporting}
                className="w-full py-3 bg-slate-50 hover:bg-[#292667] hover:text-white disabled:bg-slate-100 rounded-xl text-[9px] font-black uppercase tracking-widest transition-all border border-slate-100 flex items-center justify-center gap-2"
              >
               {isExporting ? <Loader2 size={12} className="animate-spin" /> : <Download size={12} />}
               {isExporting ? 'Exporting...' : 'Export Profile Report'}
             </button>
           </div>

           <div className="bg-[#292667] text-white rounded-3xl p-6 shadow-xl border-b-8 border-[#ec2027] flex-1 flex flex-col overflow-hidden">
             <h4 className="font-black text-[10px] uppercase tracking-[0.2em] text-[#ec2027] mb-6 flex items-center gap-2">
               <Star size={16} strokeWidth={3} className="fill-current" /> PERFORMANCE ANALYSIS
             </h4>
             <div className="space-y-6 flex-1 overflow-y-auto scrollbar-hide pr-1">
                <div className="bg-white/5 p-4 rounded-xl border border-white/5">
                   <div className="flex justify-between items-center mb-2">
                     <span className="text-[9px] font-black text-white/40 uppercase tracking-widest">Mastery Level</span>
                     <span className="text-xl font-black text-[#ec2027]">{student.finalGrade}%</span>
                   </div>
                   <div className="w-full bg-white/5 h-2 rounded-full overflow-hidden border border-white/10">
                     <div className="bg-[#ec2027] h-full transition-all duration-1000" style={{ width: `${student.finalGrade}%` }}></div>
                   </div>
                </div>
             </div>
           </div>
        </div>

        <div className="lg:col-span-8 flex flex-col gap-4 overflow-hidden">
          <div className="bg-white rounded-3xl p-6 shadow-md border border-slate-100 flex flex-col flex-1 overflow-hidden">
             <h3 className="text-xl font-black text-[#292667] uppercase tracking-tight flex items-center gap-3 mb-6">
               <div className="p-2 bg-red-50 rounded-xl text-[#ec2027]"><History size={24} strokeWidth={3} /></div> 
               Submission Records
             </h3>
             <div className="flex-1 overflow-y-auto scrollbar-hide space-y-3">
                {mockSubmissions.map((sub, i) => (
                  <div key={i} className="p-4 bg-slate-50 rounded-2xl border-2 border-transparent hover:border-indigo-100 hover:bg-white transition-all flex items-center justify-between group shadow-sm">
                    <div className="flex items-center gap-4">
                       <div className="w-10 h-10 rounded-xl bg-indigo-500 text-white flex items-center justify-center shadow-md">
                          {sub.type === 'quiz' ? <Zap size={20} fill="currentColor" /> : <ClipboardList size={20} />}
                       </div>
                       <div>
                          <h4 className="font-black text-[#292667] text-sm uppercase tracking-tight leading-none mb-1">{sub.title}</h4>
                          <p className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">{sub.date} • {sub.status}</p>
                       </div>
                    </div>
                    <div className="text-right">
                       <p className="text-[8px] font-black text-slate-300 uppercase tracking-widest mb-0.5">Score</p>
                       <p className="text-lg font-black text-[#292667]">{sub.score}</p>
                    </div>
                  </div>
                ))}
             </div>
          </div>
        </div>
      </div>
    </div>
  );
};
